language: python
python: '3.6'
sudo: false
env:
  - TOXENV=flake8
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py36
install:
  - pip install tox flake8
script:
  - tox -v
matrix:
  include:
    - python: '2.6'
      env:
        - TOXENV=py26
    - python: '2.7'
      env:
        - TOXENV=py27
    - python: '3.2'
      env:
        - TOXENV=py32
    - python: '3.3'
      env:
        - TOXENV=py33
    - python: '3.4'
      env:
        - TOXENV=py34
    - python: '3.5'
      env:
        - TOXENV=py35
    - python: '3.6'
      env:
        - TOXENV=py36
