language: python
python:
  - '3.5'
  - '3.6'
sudo: false
env:
  - TOXENV=flake8
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
install:
  - pip install tox flake8
script:
  - tox -v
